CREATE TABLE posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    user_name TEXT REFERENCES users(name) NOT NULL,
    user_userName TEXT REFERENCES users(userName) NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    zip INTEGER NOT NULL,
    comments INTEGER DEFAULT 0,
    description TEXT NOT NULL
)